### PR TITLE
Fix butterfly index

### PR DESCRIPTION
**Pull request by drammock**
fixes bug introduced in #10087

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
LGTM, let's merge once CIs come back happy!

**Comment by larsoner** [comment]
(it would be nice to have a unit test that would have caught this if you can add one without too much effort)

**Comment by drammock** [comment]
> (it would be nice to have a unit test that would have caught this if you can add one without too much effort)

I played around a bit, but actually can't reproduce the error with the Epochs testing dataset (neither `epochs` nor `epochs_full` fixtures)

**Comment by larsoner** [comment]
Okay, I took a quick look -- looks like using `raw` works

**Comment by larsoner** [comment]
@drammock looks like the `test_ica.py` failure seen on the Notebook tests is real, I can replicate locally with `pytest mne/viz/tests/test_ica.py`:
```
mne/viz/tests/test_ica.py:222: in test_plot_ica_sources
    fig = ica.plot_sources(raw)
mne/preprocessing/ica.py:1964: in plot_sources
    return plot_ica_sources(self, inst=inst, picks=picks,
mne/viz/ica.py:90: in plot_ica_sources
    fig = _plot_sources(ica, inst, picks, exclude, start=start, stop=stop,
mne/viz/ica.py:1106: in _plot_sources
    fig._draw_traces()
mne/viz/_mpl_figure.py:1721: in _draw_traces
    if self.mne.ch_selections is None and self.mne.butterfly
E   AttributeError: 'BrowserParams' object has no attribute 'ch_selections'
```

**Comment by larsoner** [comment]
Thanks @drammock !
