### ISSUE TITLE
plot_topomap() got an unexpected keyword argument 'unit'

### ISSUE THREAD

**Issue by Mirrabella** [mne-tools/mne-python#8105]
Hello, I use MNE python version 20. I found example for regression for version 11.0 https://mne.tools/0.11/auto_examples/stats/plot_sensor_regression.html, and there is very usefull parameter for plot_topomap:

def plot_topomap(x, unit):
    x.plot_topomap(ch_type='mag', scale=1, size=1.5, vmax=np.max,
                   unit=unit, times=np.linspace(0.1, 0.2, 5))

It is «unit» parameter, with it, you can change the name of the topomap color scale: write something what you need instead fT/sm.

But I cannot find this parameter in documentations, and when try to use code from example  https://mne.tools/0.11/auto_examples/stats/plot_sensor_regression.html there is an error : 
plot_topomap() got an unexpected keyword argument 'unit'.

Could you help me with that? How I can use this parameter, and change name of color scale?

**Comment by agramfort** [comment]
you cannot expect doc from version 0.11 to work with current version 0.20 version.
look at the stable documentation.

https://mne.tools/stable/auto_examples/stats/plot_sensor_regression.html
