### PR TITLE
[MRG] Fix pickling of NamedInt and NamedFloat

### LINKED ISSUE #6235: Cannot pickle mne.preprocessing.ica.ICA anymore
With the current master (installed via `pip install git+https://github.com/mne-tools/mne-python.git#egg=mne`), I get an error when pickling an `mne.preprocessing.ica.ICA` object:

```
import pickle
import mne


print(mne.__version__)
ica = mne.preprocessing.ICA()
raw = mne.io.read_raw_edf("/Users/clemens/Downloads/testfiles/S001R04.edf", preload=True)
ica.fit(raw)
pickle.loads(pickle.dumps(ica))
# Traceback (most recent call last):
#   File "/Users/clemens/Repositories/mnelab/.venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
#     exec(code_obj, self.user_global_ns, self.user_ns)
#   File "<ipython-input-8-a056623ee708>", line 1, in <module>
#     pickle.loads(pickle.dumps(ica))
# TypeError: __new__() missing 1 required positional argument: 'val'
```

The same code works with the latest released version 0.17.2. I didn't see any change to the `ICA` object that might be causing this (but maybe I'm missing something). If indeed nothing changed, could this behavior be due to how pip installs stuff from GitHub (vs. "proper" packages from PyPI)? If so, how can I fix this (I need to pickle because I want to use the `multiprocessing` module)?

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #6235.

### CODE REVIEW

**Comment by agramfort** [comment]
Please add a tiny test that just tries to pickle such a small object. Thx

**Comment by cbrnr** [comment]
LGTM complains that the first argument should be called `self` (and not `obj`). That's OK, I'll change it, but then shouldn't the first argument to `__new__` also be called `self`? Why is it called `cls` even though it is not declared as a `@classmethod`? And why doesn't LGTM complain? @agramfort @larsoner

**Comment by larsoner** [comment]
> shouldn't the first argument to __new__ also be called self? Why is it called cls even though it is not declared as a @classmethod

`__new__` is called to actually create the instance of the class, i.e. it is pretty much creating what every other method will then refer to as `self`. The naming reflects this.

I pushed a commit to simplify the `NamedInt` and `NamedFloat` classes, and add copyright to the new test file. (They don't all have it but probably should.)

**Comment by cbrnr** [comment]
OK, so `__new__` should really have `cls` as its argument name (I know it's just a naming convention). Thanks for cleaning up some more, if CIs turn green and @agramfort is happy I think this could be merged.

**Comment by larsoner** [comment]
Thanks @cbrnr
